config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "sessions#index"
  namespace :react_samples, path: '/' do
    resources :tic_tac_toe, only: [:index]
    resources :send_form, only: [:index]
    resources :temperature_meter, only: [:index]
    resources :articles, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/react_samples/articles_controller.rb
class ReactSamples::ArticlesController < ApplicationController
  def index
    @q = Article.ransack(params[:q])
    raw_articles_data = JSON.parse @q.result.page(params[:page]).per(10).to_json
    respond_to do |format|
      format.html
      format.json { render json: raw_articles_data }
    end
  end
end

app/controllers/react_samples/send_form_controller.rb
class ReactSamples::SendFormController < ApplicationController
  def index
  end
end

app/controllers/react_samples/temperature_meter_controller.rb
class ReactSamples::TemperatureMeterController < ApplicationController
  def index
  end
end

app/controllers/react_samples/tic_tac_toe_controller.rb
class ReactSamples::TicTacToeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/react_samples/articles_helper.rb
module ReactSamples::ArticlesHelper
end

app/helpers/react_samples/send_form_helper.rb
module ReactSamples::SendFormHelper
end

app/helpers/react_samples/temperature_meter_helper.rb
module ReactSamples::TemperatureMeterHelper
end

app/helpers/react_samples/tic_tac_toe_helper.rb
module ReactSamples::TicTacToeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/_base.html.slim
doctype html
html lang="ja"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title = "#{t('site_title')}"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
    = yield :head
  body
    header
      = yield :header
    main
      = yield :main
    footer
      = yield :footer
    = yield :bottom_script

app/views/layouts/application.html.slim
- content_for :header do
  nav
    ul
      li = link_to "まるばつゲーム", react_samples_tic_tac_toe_index_path
      li = link_to "フォーム送信", react_samples_send_form_index_path
      li = link_to "温度計", react_samples_temperature_meter_index_path
      li = link_to "記事テーブル", react_samples_articles_path

- content_for :main do
  = yield

- content_for :footer do
  - if request.path_info != root_path
    = link_to "トップへ戻る", root_path

= render :partial => "layouts/base"

app/views/react_samples/articles/index.html.slim
#react-samples-admin
  .sidebar
    .logo
      = link_to "React Sample", root_path
    .menu-list
      ul
        li
          i.fa.fa-home
          | Home
        li
          i.fa.fa-tachometer
          | Dashboard
        li
          i.fa.fa-users
          | Prospects
        li.current
          i.fa.fa-file-text
          | Articles
        li
          i.fa.fa-line-chart
          | Report
        li
          i.fa.fa-cog
          | Settings

  .content
    .navigation-bar
      ul
        li = link_to "F.Shibusawa", root_path, class: "user-name"

    #article-table-root

- content_for :bottom_script do
  = javascript_pack_tag "react_samples/articles"

app/views/react_samples/send_form/index.html.slim
#grid-root

- content_for :bottom_script do
  = javascript_pack_tag "react_samples/send_form"

app/views/react_samples/temperature_meter/index.html.slim
#temperature-root

- content_for :bottom_script do
  = javascript_pack_tag "react_samples/temperature_meter"

app/views/react_samples/tic_tac_toe/index.html.slim
h1 = "#{t('site_title')}"
#game

- content_for :bottom_script do
  = javascript_pack_tag "react_samples/tic_tac_toe"